export const en = {
  translation: {
    brand: 'Robinho', subtitle: 'Intelligent Screening Engine · Minerva Foods',
    nav: { dashboard: 'Dashboard', params: 'Parameters', triagem: 'CSV Screening', results: 'Results', whatsapp: 'WhatsApp', config: 'Settings' },
    dashboard: { title: 'Recruitment Pipeline', sub: 'Executive view · Updated after each screening', newTriagem: '+ New Screening', total: 'Total Screened', aprovados: 'Approved', potenciais: 'Potential', reprovados: 'Rejected', scoreMedio: 'Average Score', funil: 'Screening Funnel', top5: 'Top 5 Candidates', noData: 'Run a screening to see data here.' },
    params: { title: 'Screening Parameters', sub: 'Configure dimensions, weights and thresholds before starting', processo: 'Process Name', responsavel: 'Responsible', cargo: 'Target Position', sensibilidade: 'Similarity Sensitivity', sens_strict: 'Strict — exact words', sens_normal: 'Normal — includes variations', sens_flex: 'Flexible — roots and synonyms', descritivo: 'Job Description', descritivo_ph: 'Paste the full job description here...', analisar: 'Analyze and Propagate Terms', limiar_ap: 'Minimum Score — Approved', limiar_pot: 'Minimum Score — Potential', salvar: 'Save Configuration', balancear: 'Auto-balance to 100', restaurar: 'Restore Defaults', testar: 'Run Validation Test', termos: 'Automatically extracted terms', peso: 'pts' },
    triagem: { title: 'CSV Candidate Screening', sub: 'Upload → Map → Automatic analysis', dropzone: 'Click to select or drag the spreadsheet', dropzone_sub: 'Formats: CSV, XLSX, XLSM, XLS · Max. 50 MB', mapeamento: 'Column Mapping', colunas: 'columns', candidatos: 'candidates', iniciar: 'Start Intelligent Screening', processando: 'Processing candidates...', step1: 'Config', step2: 'Upload', step3: 'Map', step4: 'Results', col_nome: 'Candidate Name', col_tel: 'Phone / WhatsApp', col_email: 'E-mail', col_linkedin: 'LinkedIn URL', col_cargo: 'Current Position', col_empresa: 'Current Company', col_cidade: 'City', col_exp: 'Work Experience History', col_form: 'Academic Background', col_idiomas: 'Languages', col_salario: 'Expected Salary' },
    results: { title: 'Screening Results', todos: 'All candidates', aprovados: '✅ Approved', potenciais: '⚡ Potential', reprovados: '❌ Rejected', exportar: 'Export CSV', rank: '#', nome: 'Name', score: 'Score', classe: 'Classification', destaque: '⭐', cargo: 'Current Position', cidade: 'City', telefone: 'Phone', linkedin: 'LinkedIn', acao: 'Action', classificacao: { aprovado: '✅ Approved', potencial: '⚡ Potential', reprovado: '❌ Rejected' } },
    whatsapp: { title: 'Automated WhatsApp', sub: 'Personalized messaging by classification', msg_ap: 'Message — Approved', msg_pot: 'Message — Potential', msg_rep: 'Message — Rejected', preview: 'Preview', disparar: 'Send Messages to Screened Candidates', delay: 'Delay between messages', auto_ap: 'Auto-send to Approved', auto_pot: 'Auto-send to Potential', auto_rep: 'Auto-send to Rejected' },
    config: { title: 'Settings & APIs', sub: 'Integrations and global system settings', gupy_key: 'API Key — Gupy', wpp_key: 'API Key — WhatsApp Business', wpp_num: 'WhatsApp Origin Number', testar: 'Test', versao: 'Version', ambiente: 'Environment', prod: 'Production', hom: 'Staging', debug: 'Debug Mode', historico: 'Save screening history', idioma_sistema: 'System Language' },
    common: { salvo: '✅ Configuration saved successfully!', erro: '❌ Save error. Check your connection.', auto: 'Auto', nao_mapear: '— Do not map —', mapear: '— Map after upload —', sim: 'Yes', nao: 'No', exportado: '✅ CSV exported!', gupy_wip: 'Gupy integration coming soon.' }
  }
}
