export const pt = {
  translation: {
    brand: 'Robinho', subtitle: 'Motor de Triagem Inteligente · Minerva Foods',
    nav: { dashboard: 'Dashboard', params: 'Parâmetros', triagem: 'Triagem CSV', results: 'Resultados', whatsapp: 'WhatsApp', config: 'Configurações' },
    dashboard: { title: 'Pipeline de Recrutamento', sub: 'Visão executiva · Atualizado após cada triagem', newTriagem: '+ Nova Triagem', total: 'Total Triados', aprovados: 'Aprovados', potenciais: 'Potenciais', reprovados: 'Reprovados', scoreMedio: 'Score Médio', funil: 'Funil de Triagem', top5: 'Top 5 Candidatos', noData: 'Realize uma triagem para visualizar.' },
    params: { title: 'Parâmetros de Triagem', sub: 'Configure dimensões, pesos e limiares antes de iniciar', processo: 'Nome do Processo', responsavel: 'Responsável', cargo: 'Cargo Buscado', sensibilidade: 'Sensibilidade de Similaridade', sens_strict: 'Rigorosa — palavras exatas', sens_normal: 'Normal — inclui variações', sens_flex: 'Flexível — radicais e sinônimos', descritivo: 'Descritivo do Cargo', descritivo_ph: 'Cole aqui o descritivo completo da vaga...', analisar: 'Analisar e Propagar Termos', limiar_ap: 'Score Mínimo — Aprovado', limiar_pot: 'Score Mínimo — Potencial', salvar: 'Salvar Configuração', balancear: 'Auto-balancear para 100', restaurar: 'Restaurar Padrões', testar: 'Executar Teste de Validação', termos: 'Termos extraídos automaticamente', peso: 'pts' },
    triagem: { title: 'Triagem de Currículos via CSV', sub: 'Upload → Mapeamento → Análise automática', dropzone: 'Clique para selecionar ou arraste a planilha', dropzone_sub: 'Formatos: CSV, XLSX, XLSM, XLS · Máx. 50 MB', mapeamento: 'Mapeamento de Colunas', colunas: 'colunas', candidatos: 'candidatos', iniciar: 'Iniciar Triagem Inteligente', processando: 'Processando candidatos...', step1: 'Config', step2: 'Upload', step3: 'Mapear', step4: 'Resultados', col_nome: 'Nome do Candidato', col_tel: 'Telefone / WhatsApp', col_email: 'E-mail', col_linkedin: 'LinkedIn URL', col_cargo: 'Cargo Atual', col_empresa: 'Empresa Atual', col_cidade: 'Cidade', col_exp: 'Histórico de Experiências', col_form: 'Formação Acadêmica', col_idiomas: 'Idiomas', col_salario: 'Pretensão Salarial' },
    results: { title: 'Resultados da Triagem', todos: 'Todos os candidatos', aprovados: '✅ Aprovados', potenciais: '⚡ Potenciais', reprovados: '❌ Reprovados', exportar: 'Exportar CSV', rank: '#', nome: 'Nome', score: 'Score', classe: 'Classificação', destaque: '⭐', cargo: 'Cargo Atual', cidade: 'Cidade', telefone: 'Telefone', linkedin: 'LinkedIn', acao: 'Ação', classificacao: { aprovado: '✅ Aprovado', potencial: '⚡ Potencial', reprovado: '❌ Reprovado' } },
    whatsapp: { title: 'WhatsApp Automático', sub: 'Disparo de mensagens personalizadas por classificação', msg_ap: 'Mensagem — Aprovado', msg_pot: 'Mensagem — Potencial', msg_rep: 'Mensagem — Reprovado', preview: 'Prévia', disparar: 'Disparar Mensagens para Triados', delay: 'Delay entre disparos', auto_ap: 'Disparar Aprovados automaticamente', auto_pot: 'Disparar Potenciais automaticamente', auto_rep: 'Disparar Reprovados automaticamente' },
    config: { title: 'Configurações & APIs', sub: 'Integrações e ajustes globais do sistema', gupy_key: 'API Key — Gupy', wpp_key: 'API Key — WhatsApp Business', wpp_num: 'Número WhatsApp Origem', testar: 'Testar', versao: 'Versão', ambiente: 'Ambiente', prod: 'Produção', hom: 'Homologação', debug: 'Modo Debug', historico: 'Salvar histórico de triagens', idioma_sistema: 'Idioma do Sistema' },
    common: { salvo: '✅ Configuração salva com sucesso!', erro: '❌ Erro ao salvar. Verifique sua conexão.', auto: 'Auto', nao_mapear: '— Não mapear —', mapear: '— Mapear após upload —', sim: 'Sim', nao: 'Não', exportado: '✅ CSV exportado!', gupy_wip: 'Integração com Gupy em desenvolvimento.' }
  }
}
